version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: pessoa
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker
    networks:
      - production-network
    ports:
      - "5432:5432"

networks:
  production-network:
    driver: bridge